trigger:
  branches:
    include:
      - "*"
    exclude:
      - main
  paths:
    exclude:
      - readme.md

variables:
  System.Debug: false

  # Project name
  projectName: "hermes-proj"

  # KeyVault name. Must match KeyVault name form Permanet Infrastructure Pipeline.
  keyVaultName: "hermes-proj-keyvault"

  # Function app name
  functionAppName: "func-$(projectName)"

  # Environment production status - dev/prod/etc
  environment: dev

  # Subscription ID for target resource group
  subscriptionId: 1192dbda-03e9-417a-8c81-7487e3525752

  # Service connection Name for target resource group
  azureResourceManagerConnection: Azure Hermes Project Dev

  # Name of a target resource group for all resources
  resourceGroupName: rg-hermes-project-dev-00

  # Agent VM image name
  vmImageName: "ubuntu-20.04"

  # Working Directory
  workingDirectory: "$(System.DefaultWorkingDirectory)/"

extends:
  template: pipeline.yml
