# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - "az_pipeline_main/*"

variables:
  # Project name
  projectName: "hermes-proj"

  # KeyVault name. Must match KeyVault name form Permanet Infrastructure Pipeline.
  keyVaultName: "hermes-proj-keyvault"

  # Agent VM image name
  vmImageName: "ubuntu-20.04"

  # Working Directory
  workingDirectory: "$(System.DefaultWorkingDirectory)/"

stages:
  - stage: Provision
    displayName: Provision Azure resources from ARM template

    jobs:
      - job: DeployARM
        displayName: Deploy ARM template
        pool:
          vmImage: $(vmImageName)

        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: 'Azure Hermes Project Permanent Infrastructure'
              subscriptionId: '1192dbda-03e9-417a-8c81-7487e3525752'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'hermes-project-permanent'
              location: 'North Europe'
              templateLocation: 'Linked artifact'
              csmFile: 'az_pipeline_permanent/azuredeploy.json'
              csmParametersFile: 'az_pipeline_permanent/azuredeploy.parameters.json'
              overrideParameters: '-functionAppName $(functionAppName)'
              deploymentMode: 'Complete'
