# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
      - "*"
  paths:
    exclude:
      - "az_pipeline_permanent/*"

variables:
  # Project name
  projectName: "hermes-proj"

  # KeyVault name. Must match KeyVault name form Permanet Infrastructure Pipeline.
  keyVaultName: "hermes-proj-keyvault"

  # Function app name
  functionAppName: "func-$(projectName)"

  # Environment production status - dev/prod/etc
  environment: dev

  # Subscription ID for target resource group
  subscriptionId: 1192dbda-03e9-417a-8c81-7487e3525752

  # Service connection Name for target resource group
  azureResourceManagerConnection: Azure Hermes Project Dev

  # Name of a target resource group for all resources
  resourceGroupName: rg-hermes-project-dev-00

  # Agent VM image name
  vmImageName: "ubuntu-20.04"

  # Working Directory
  workingDirectory: "$(System.DefaultWorkingDirectory)/"

stages:
  - stage: Provision
    displayName: Provision Azure resources from ARM template
    jobs:
      - job: Provisioning
        displayName: Provisioning
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: Deploying permanant / stateful resources
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: $(azureResourceManagerConnection)
              subscriptionId: $(subscriptionId)
              location: "North Europe"
              action: "Create Or Update Resource Group"
              resourceGroupName: $(resourceGroupName)
              templateLocation: "Linked artifact"
              csmFile: "az_pipeline_permanent/azuredeploy.json"
              csmParametersFile: "az_pipeline_permanent/azuredeploy.parameters.json"
              overrideParameters: "-keyVaultName $(keyVaultName)"
              deploymentMode: "Incremental"
          - task: AzurePowerShell@5
            inputs:
              azureSubscription: $(azureResourceManagerConnection)
              displayName: Check prerequisites for main resources template
              ScriptType: "InlineScript"
              Inline: |
                Import-Module .\DeploymentHelperFunctions.ps1
                Test-KeyVaultReadiness -KeyVaultName $(keyVaultName) -MandatorySecretsList @('telegramFunctionPermanentKey', 'telegramBotToken')
              FailOnStandardError: true
              azurePowerShellVersion: "LatestVersion"
          - task: AzureKeyVault@1
            inputs:
              azureSubscription: $(azureResourceManagerConnection)
              KeyVaultName: "$(keyVaultName)"
              SecretsFilter: "telegramFunctionPermanentKey, telegramBotToken"
              RunAsPreJob: false
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: "Resource Group"
              azureResourceManagerConnection: $(azureResourceManagerConnection)
              subscriptionId: $(subscriptionId)
              location: "North Europe"
              action: "Create Or Update Resource Group"
              resourceGroupName: $(resourceGroupName)
              templateLocation: "Linked artifact"
              csmFile: "az_pipeline_main/azuredeploy.json"
              overrideParameters: "-projectName $(projectName) -functionAppName $(functionAppName) -telegramFunctionPermanentKey $(telegramFunctionPermanentKey) -keyVaultName $(keyVaultName) -environment $(environment)"
              deploymentMode: "Incremental"
          - publish: $(workingDirectory)/DeploymentHelperFunctions.ps1
            artifact: drop

  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - bash: |
              if [ -f extensions.csproj ]
              then
                  dotnet build extensions.csproj --runtime ubuntu.16.04-x64 --output ./bin
              fi
            workingDirectory: $(workingDirectory)
            displayName: "Build extensions"
          - task: UsePythonVersion@0
            displayName: "Use Python 3.7"
            inputs:
              versionSpec: 3.7
          - bash: |
              python -m venv worker_venv
              source worker_venv/bin/activate
              pip install -r requirements.txt
            workingDirectory: $(workingDirectory)
            displayName: "Install application dependencies"
          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(workingDirectory)"
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true
          - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop
  - stage: Deploy
    displayName: Deploy stage
    dependsOn:
      - Provision
      - Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Deploy
        environment: $(environment)
        pool:
          vmImage: $(vmImageName)
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureFunctionApp@1
                  displayName: "Azure functions app deploy"
                  inputs:
                    azureSubscription: "Azure Hermes Project Dev"
                    appType: "functionAppLinux"
                    appName: "$(functionAppName)"
                    package: "$(Pipeline.Workspace)/drop/$(Build.BuildId).zip"
                    runtimeStack: "PYTHON|3.7"
                - task: AzureKeyVault@1
                  inputs:
                    azureSubscription: $(azureResourceManagerConnection)
                    KeyVaultName: "$(keyVaultName)"
                    SecretsFilter: "telegramFunctionPermanentKey, telegramBotToken"
                    RunAsPreJob: false
                - task: PowerShell@2
                  displayName: Register callback WebHook in Telegram API
                  inputs:
                    targetType: "inline"
                    script: |
                      Import-Module "$(Pipeline.Workspace)/drop/DeploymentHelperFunctions.ps1
                      Register-TelegramWebhookUrl -TelegramBotToken $(telegramBotToken) -FunctionAppName $(functionAppName) -FunctionKey $(telegramFunctionPermanentKey)
